baseurl = "https://www.memocenose.com/"
title = "MemoCenose"
author = "Meme"
canonifyurls = true
languagecode = "fr"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Memocenose"


